apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCHv3OyVGbvs/m0lPaC3QA193MoBLB8vK5qDQ967FoovEqDMK82M3N9Ldrs/e2pIjsh5gs7szc4byIfcliqUgu+GlpKdyVLHhMnM1Bcm4ZQutC6/AQ/ieir46U8+y6WopM3qUnkrKZHGJfGz5ntmDhPk14JmLXBcEjdLoVuFY0WdF0I4laIEamDua7WZeNp93kRFtTYAEO9Y3mfIANC0ctJ9JVMykpwIhHCRdaqXjcHufIc/A9F29ZilfN3JUoaIqpOywc6sGcp0o3L6aI1Ld51LHbZib+o9i70EvJnOCgtafoEAj0kalazNo82aqPim3gc4UsySVLt/B1SFT39MT4RCRsFWVQFLP5GehjIV5eIpuf7ApjLNlIJeLGbNpnNisljfHCawBwbfxg7NAZlu8D1rh9a59YJZou3+5VBFXz0M9ZOBe1WCSiGv+5VBvZkrJxE9JmEAFLKGPZEZUzsKWSsKnSQQKYnnS1ayrjv6pf0cfer4yXcTFXU+LHJz3wb+mygZtcycbQLuLbn6RxVhyQmnD5VkEoxr/876vgIKrniM89b0GwbNEaDUtCBSiHYJL9xb6h/JUBgi36hu6s0IT4lt48e89T6af55Wve15xPB5Sx8hy8h4AEMYvYjh/DNXv718XQWmVIRfduaBy9ENGRRolRaTYGf/j7hXSoznufMTanNZ7HpmmdAGFUpQb2bamdOypg6L2AKvO6FMO9Xjv5+S71boI3QZWCv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

