apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:a9dvF+Cwj/gvXAarGqNXpR4RWzwdf/rhcA==,iv:rAeoQH11lidYBZQ3CsKPAmvopBMvkHBKYihaavmA7IY=,tag:BuWbhmlGFaqtXVboLOob0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-23T20:30:18Z"
    mac: ENC[AES256_GCM,data:xrCd6Lllb0ueqZU4VJHbb2hJNg0O54EXpehhAKAW/cLSsczL3jaEfPHDVG4ctnubgTbHTV8XWZp7Q81fdDydwGCVqeQXtlWLIEgB4+xNzqX5CEHS3rAszh0dJXu0zoelIZxrNeTnu70dwfvlbtrlqW13ag8IiNlU6re+kY+rs8c=,iv:T+UdRFxLm1tU55bpYqDBHQ/h0RMlTRAvH9jVIT+OJRY=,tag:ejobugCtFzdY5PvY++fkYA==,type:str]
    pgp:
        - created_at: "2025-12-23T20:30:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA3kOCzTOnvGjAQv/QEaK6Wcdf0A5rm5n9eGsXZPz5w+ZWjbH+UVt/FhxIwGL
            2w9DJE6/mGCcR4sPVzuaUUrut5vn/yhK2GR1j3/NEy3o5Hw/0JIkdjgFAOD7rZWu
            oSmahjURz9xpqlQQ3XCqrIk1ZfUDS1QRLH0JV++oy4vvKU2MjpnbFgJmHnRyLNie
            SjF5aBZPtYRtwquxKo/68q8kOQUBR+dND2SQ4oRgCs5S5ROSS73dL/RjMFUiNvNO
            NGhHmRuy86QsOsYP8+CuG+gaKObn9XPFkOox6hW6z+8EtIrpNhvy04G1uJcydlxU
            rs0diM4GtFRYdG4ML22Mz4O6IVbY6VPNeQnQ+w/mGB6SW9LkQqWqWX2pWUW/2TIl
            DsyIVjY1v3x469MNQ1RcSx1ieGXTPzdP7WpEjlRiOnvITAlNsUwzKhZnJh0E0ZDk
            sIfIHQQg6GcL2AqCwmH26CyvkqC4cYcL2vDjEy4ouk/Ejtr+cdMyRNnd1i5+oINR
            BvPYg9MYitnPVdmyW4qg1GgBCQIQu0kKI3g+BS1SU6kvZoi3WuTk6bOYwHMys7w/
            qbqNc6gIsQM/mekldPBoelB18TKY4mTXZN8UtJmkm5HJd+u9Q4IQjbCz+qn5J4f4
            pzwtRACbr9BqHEhZNNf0gPAryBdNj3DudA==
            =p0/I
            -----END PGP MESSAGE-----
          fp: 67E846C8AEC9271D9C278051E18ACBD4A6EB6DDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
